// Copyright (c) 2025-2026, Audionut and the autobrr contributors.
// SPDX-License-Identifier: GPL-2.0-or-later

package metautil

import (
	"fmt"
	"strings"
	"unicode"
)

// ISO639PortugueseName returns the Portuguese-language display name for an
// ISO 639-1 two-letter language code.  When the code is not recognized,
// fallback is returned instead.
func ISO639PortugueseName(code, fallback string) string {
	code = strings.ToLower(strings.TrimSpace(code))
	if code == "" {
		return fallback
	}
	if name, ok := iso639PTBR[code]; ok {
		return name
	}
	return fallback
}

// ISO3166PortugueseName returns the Portuguese-language display name for an
// ISO 3166-1 alpha-2 country code.  When the code is not recognized,
// fallback is returned instead.
func ISO3166PortugueseName(code, fallback string) string {
	code = strings.ToUpper(strings.TrimSpace(code))
	if code == "" {
		return fallback
	}
	if name, ok := iso3166PTBR[code]; ok {
		return name
	}
	return fallback
}

var iso3166PTBR = map[string]string{
	"AD": "Andorra",
	"AE": "Emirados Árabes Unidos",
	"AF": "Afeganistão",
	"AG": "Antígua e Barbuda",
	"AI": "Anguila",
	"AL": "Albânia",
	"AM": "Armênia",
	"AO": "Angola",
	"AQ": "Antártida",
	"AR": "Argentina",
	"AS": "Samoa Americana",
	"AT": "Áustria",
	"AU": "Austrália",
	"AW": "Aruba",
	"AX": "Ilhas Aland",
	"AZ": "Azerbaijão",
	"BA": "Bósnia e Herzegovina",
	"BB": "Barbados",
	"BD": "Bangladesh",
	"BE": "Bélgica",
	"BF": "Burquina Faso",
	"BG": "Bulgária",
	"BH": "Bahrein",
	"BI": "Burundi",
	"BJ": "Benin",
	"BL": "São Bartolomeu",
	"BM": "Bermudas",
	"BN": "Brunei",
	"BO": "Bolívia",
	"BQ": "Países Baixos Caribenhos",
	"BR": "Brasil",
	"BS": "Bahamas",
	"BT": "Butão",
	"BV": "Ilha Bouvet",
	"BW": "Botsuana",
	"BY": "Bielorrússia",
	"BZ": "Belize",
	"CA": "Canadá",
	"CC": "Ilhas Cocos (Keeling)",
	"CD": "Congo - Kinshasa",
	"CF": "República Centro-Africana",
	"CG": "República do Congo",
	"CH": "Suíça",
	"CI": "Costa do Marfim",
	"CK": "Ilhas Cook",
	"CL": "Chile",
	"CM": "Camarões",
	"CN": "China",
	"CO": "Colômbia",
	"CR": "Costa Rica",
	"CU": "Cuba",
	"CV": "Cabo Verde",
	"CW": "Curaçao",
	"CX": "Ilha Christmas",
	"CY": "Chipre",
	"CZ": "Tchéquia",
	"DE": "Alemanha",
	"DJ": "Djibuti",
	"DK": "Dinamarca",
	"DM": "Dominica",
	"DO": "República Dominicana",
	"DZ": "Argélia",
	"EC": "Equador",
	"EE": "Estônia",
	"EG": "Egito",
	"EH": "Saara Ocidental",
	"ER": "Eritreia",
	"ES": "Espanha",
	"ET": "Etiópia",
	"FI": "Finlândia",
	"FJ": "Fiji",
	"FK": "Ilhas Malvinas",
	"FM": "Micronésia",
	"FO": "Ilhas Faroe",
	"FR": "França",
	"GA": "Gabão",
	"GB": "Reino Unido",
	"GD": "Granada",
	"GE": "Georgia",
	"GF": "Guiana Francesa",
	"GG": "Guernsey",
	"GH": "Gana",
	"GI": "Gibraltar",
	"GL": "Groenlândia",
	"GM": "Gâmbia",
	"GN": "Guiné",
	"GP": "Guadalupe",
	"GQ": "Guiné Equatorial",
	"GR": "Grécia",
	"GS": "Ilhas Geórgia do Sul e Sandwich do Sul",
	"GT": "Guatemala",
	"GU": "Guam",
	"GW": "Guiné-Bissau",
	"GY": "Guiana",
	"HK": "Hong Kong, RAE da China",
	"HM": "Ilhas Heard e McDonald",
	"HN": "Honduras",
	"HR": "Croácia",
	"HT": "Haiti",
	"HU": "Hungria",
	"ID": "Indonésia",
	"IE": "Irlanda",
	"IL": "Israel",
	"IM": "Ilha de Man",
	"IN": "Índia",
	"IO": "Território Britânico do Oceano Índico",
	"IQ": "Iraque",
	"IR": "Irã",
	"IS": "Islândia",
	"IT": "Itália",
	"JE": "Jersey",
	"JM": "Jamaica",
	"JO": "Jordânia",
	"JP": "Japão",
	"KE": "Quênia",
	"KG": "Quirguistão",
	"KH": "Camboja",
	"KI": "Quiribati",
	"KM": "Comores",
	"KN": "São Cristóvão e Névis",
	"KP": "Coreia do Norte",
	"KR": "Coreia do Sul",
	"KW": "Kuwait",
	"KY": "Ilhas Cayman",
	"KZ": "Cazaquistão",
	"LA": "Laos",
	"LB": "Líbano",
	"LC": "Santa Lúcia",
	"LI": "Liechtenstein",
	"LK": "Sri Lanka",
	"LR": "Libéria",
	"LS": "Lesoto",
	"LT": "Lituânia",
	"LU": "Luxemburgo",
	"LV": "Letônia",
	"LY": "Líbia",
	"MA": "Marrocos",
	"MC": "Mônaco",
	"MD": "Moldova",
	"ME": "Montenegro",
	"MF": "São Martinho",
	"MG": "Madagascar",
	"MH": "Ilhas Marshall",
	"MK": "Macedônia do Norte",
	"ML": "Mali",
	"MM": "Mianmar (Birmânia)",
	"MN": "Mongólia",
	"MO": "Macau, RAE da China",
	"MP": "Ilhas Marianas do Norte",
	"MQ": "Martinica",
	"MR": "Mauritânia",
	"MS": "Montserrat",
	"MT": "Malta",
	"MU": "Maurício",
	"MV": "Maldivas",
	"MW": "Malaui",
	"MX": "México",
	"MY": "Malásia",
	"MZ": "Moçambique",
	"NA": "Namíbia",
	"NC": "Nova Caledônia",
	"NE": "Níger",
	"NF": "Ilha Norfolk",
	"NG": "Nigéria",
	"NI": "Nicarágua",
	"NL": "Países Baixos",
	"NO": "Noruega",
	"NP": "Nepal",
	"NR": "Nauru",
	"NU": "Niue",
	"NZ": "Nova Zelândia",
	"OM": "Omã",
	"PA": "Panamá",
	"PE": "Peru",
	"PF": "Polinésia Francesa",
	"PG": "Papua-Nova Guiné",
	"PH": "Filipinas",
	"PK": "Paquistão",
	"PL": "Polônia",
	"PM": "São Pedro e Miquelão",
	"PN": "Ilhas Pitcairn",
	"PR": "Porto Rico",
	"PS": "Territórios palestinos",
	"PT": "Portugal",
	"PW": "Palau",
	"PY": "Paraguai",
	"QA": "Catar",
	"RE": "Reunião",
	"RO": "Romênia",
	"RS": "Sérvia",
	"RU": "Rússia",
	"RW": "Ruanda",
	"SA": "Arábia Saudita",
	"SB": "Ilhas Salomão",
	"SC": "Seicheles",
	"SD": "Sudão",
	"SE": "Suécia",
	"SG": "Singapura",
	"SH": "Santa Helena",
	"SI": "Eslovênia",
	"SJ": "Svalbard e Jan Mayen",
	"SK": "Eslováquia",
	"SL": "Serra Leoa",
	"SM": "San Marino",
	"SN": "Senegal",
	"SO": "Somália",
	"SR": "Suriname",
	"SS": "Sudão do Sul",
	"ST": "São Tomé e Príncipe",
	"SV": "El Salvador",
	"SX": "Sint Maarten",
	"SY": "Síria",
	"SZ": "Essuatíni",
	"TC": "Ilhas Turcas e Caicos",
	"TD": "Chade",
	"TF": "Territórios Franceses do Sul",
	"TG": "Togo",
	"TH": "Tailândia",
	"TJ": "Tadjiquistão",
	"TK": "Tokelau",
	"TL": "Timor-Leste",
	"TM": "Turcomenistão",
	"TN": "Tunísia",
	"TO": "Tonga",
	"TR": "Turquia",
	"TT": "Trinidad e Tobago",
	"TV": "Tuvalu",
	"TW": "Taiwan",
	"TZ": "Tanzânia",
	"UA": "Ucrânia",
	"UG": "Uganda",
	"UM": "Ilhas Menores Distantes dos EUA",
	"US": "Estados Unidos da América",
	"UY": "Uruguai",
	"UZ": "Uzbequistão",
	"VA": "Cidade do Vaticano",
	"VC": "São Vicente e Granadinas",
	"VE": "Venezuela",
	"VG": "Ilhas Virgens Britânicas",
	"VI": "Ilhas Virgens Americanas", //nolint:misspell
	"VN": "Vietnã",
	"VU": "Vanuatu",
	"WF": "Wallis e Futuna",
	"WS": "Samoa",
	"YE": "Iêmen",
	"YT": "Mayotte",
	"ZA": "África do Sul",
	"ZM": "Zâmbia",
	"ZW": "Zimbábue",
}

// ParseDimensionStr extracts numeric digits from a value that may contain
// formatting like "1 920" or "1,920".  It returns a string of pure digits,
// or "" when no digits are found.
func ParseDimensionStr(val any) string {
	if val == nil {
		return ""
	}
	s := fmt.Sprintf("%v", val)
	var digits strings.Builder
	for _, r := range s {
		if r >= '0' && r <= '9' {
			digits.WriteRune(r)
		}
	}
	return digits.String()
}

// iso639PTBR maps ISO 639-1 codes to Portuguese display names.
var iso639PTBR = map[string]string{
	"aa": "Afar",
	"ab": "Abcázio",
	"ae": "Avéstico",
	"af": "Africânder",
	"ak": "Acã",
	"am": "Amárico",
	"an": "Aragonês",
	"ar": "Árabe",
	"as": "Assamês",
	"av": "Avárico",
	"ay": "Aimará",
	"az": "Azerbaijano",
	"ba": "Basquir",
	"be": "Bielorrusso",
	"bg": "Búlgaro",
	"bh": "Maithili",
	"bi": "Bislamábichlamar",
	"bm": "Bâmbara",
	"bn": "Bengali ou bangla",
	"bo": "Tibetano",
	"br": "Bretão",
	"bs": "Bósnio",
	"ca": "Catalão",
	"ce": "Tchechenoou checheno",
	"ch": "Chamorro",
	"co": "Corso",
	"cr": "Cree",
	"cs": "Tcheco",
	"cu": "Eslavo eclesiástico",
	"cv": "Tchuvache",
	"cy": "Galês",
	"da": "Dinamarquês",
	"de": "Alemão",
	"dv": "Diveí",
	"dz": "Dzongkha",
	"ee": "Jeje",
	"el": "Grego moderno(desde 1453)",
	"en": "Inglês",
	"eo": "Esperanto",
	"es": "Castelhano",
	"et": "Estoniano",
	"eu": "Basco",
	"fa": "Persa",
	"ff": "Fula",
	"fi": "Finlandês",
	"fj": "Fidjiano",
	"fo": "Feroêsou feróico",
	"fr": "Francês",
	"fy": "Frisãoocidental",
	"ga": "Irlandês",
	"gd": "Gaélico escocês",
	"gl": "Galego",
	"gn": "Guarani",
	"gu": "Gujarati",
	"gv": "Manês",
	"ha": "Hauçá",
	"he": "Hebraico",
	"hi": "Hindi",
	"ho": "Hiri Motu",
	"hr": "Croata",
	"ht": "Crioulo haitiano",
	"hu": "Húngaro",
	"hy": "Armênio",
	"hz": "Hereró",
	"ia": "Interlíngua",
	"id": "Indonésio",
	"ie": "Interlíngua",
	"ig": "Ibo",
	"ii": "YideSichuan",
	"ik": "Inupiaq",
	"io": "Ido",
	"is": "Islandês",
	"it": "Italiano",
	"iu": "Inuktitut",
	"ja": "Japonês",
	"jv": "Javanês",
	"ka": "Georgiano",
	"kg": "Kongo",
	"ki": "Kikuyu",
	"kj": "Oshikwanyama",
	"kk": "Cazaque",
	"kl": "Groenlandês",
	"km": "Khmer",
	"kn": "Canarês",
	"ko": "Coreano",
	"kr": "Kanuri ou canúri",
	"ks": "Caxemir",
	"ku": "Curdo",
	"kv": "Komi",
	"kw": "Córnico",
	"ky": "Quirguiz",
	"la": "Latim",
	"lb": "Luxemburguês",
	"lg": "Luganda",
	"li": "Limburguês",
	"ln": "Lingala",
	"lo": "Laociano",
	"lt": "Lituano",
	"lu": "Luba-catanga",
	"lv": "Letão",
	"mg": "Malgaxe",
	"mh": "Marshallês",
	"mi": "Maori",
	"mk": "Macedônio",
	"ml": "Malaiala",
	"mn": "Mongol",
	"mo": "Moldavo",
	"mr": "Marata",
	"ms": "Malaio",
	"mt": "Maltês",
	"my": "Birmanês",
	"na": "Nauruano",
	"nb": "Bokmål norueguês",
	"nd": "Ndebele do norte",
	"ne": "Nepali, nepalês",
	"ng": "Ndonga",
	"nl": "Holandês",
	"nn": "Novo norueguês",
	"no": "Norueguês",
	"nr": "Ndebele do sul",
	"nv": "Navajo",
	"ny": "Nianja",
	"oc": "Occitano(depois 1500)",
	"oj": "Chippewa",
	"om": "Oromo",
	"or": "Oriá",
	"os": "Oseto",
	"pa": "Panjabi",
	"pi": "Páli",
	"pl": "Polaco",
	"ps": "Pachto",
	"pt": "Português",
	"qu": "Quíchua",
	"rm": "Reto-romano",
	"rn": "Kirundi",
	"ro": "Romeno",
	"ru": "Russo",
	"rw": "Quiniaruanda",
	"sa": "Sânscrito",
	"sc": "Sardo",
	"sd": "Sindi",
	"se": "Samido norte",
	"sg": "Sango",
	"sh": "Servo-croata",
	"si": "Cingalês",
	"sk": "Eslovaco",
	"sl": "Esloveno",
	"sm": "Samoano",
	"sn": "Chona",
	"so": "Somali",
	"sq": "Albanês",
	"sr": "Sérvio",
	"ss": "Suázi",
	"st": "Soto do sul",
	"su": "Sundanês",
	"sv": "Sueco",
	"sw": "Suaíli",
	"ta": "Tâmil",
	"te": "Telugu",
	"tg": "Tajique",
	"th": "Tailandês",
	"ti": "Tigrínia",
	"tk": "Turcomano",
	"tl": "Tagalo",
	"tn": "Tswana",
	"to": "Tonganês",
	"tr": "Turco",
	"ts": "Tsonga",
	"tt": "Tártaro",
	"tw": "Twi",
	"ty": "Taitiano",
	"ug": "Uigur",
	"uk": "Ucraniano",
	"ur": "Urdu",
	"uz": "Uzbeque",
	"ve": "Venda",
	"vi": "Vietnamita",
	"vo": "Volapuque",
	"wa": "Valão",
	"wo": "Uolofe",
	"xh": "Xhosa",
	"yi": "Iídiche",
	"yo": "Iorubá",
	"za": "Zhuang",
	"zh": "Chinês",
	"zu": "Zulu",
}

// TranslateGenreToPortuguese maps a genre string from English to Portuguese if a translation exists.
// Otherwise it returns the genre as-is.
func TranslateGenreToPortuguese(genre string) string {
	cleaned := strings.ToLower(strings.TrimSpace(genre))
	if translated, ok := EnglishToPortugueseGenre[cleaned]; ok {
		return translated
	}
	return genre
}

// TranslateGenreToPortugueseStrict maps an English genre string to Portuguese.
// It returns the translated string, or "" if no translation is found.
func TranslateGenreToPortugueseStrict(genre string) string {
	cleaned := strings.ToLower(strings.TrimSpace(genre))
	if translated, ok := EnglishToPortugueseGenre[cleaned]; ok {
		return translated
	}
	return ""
}

// CapitalizeGenre capitalizes the first letter of a genre string.
func CapitalizeGenre(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// EnglishToPortugueseGenre maps English genre tags to Portuguese.
var EnglishToPortugueseGenre = map[string]string{
	"action & adventure":         "ação e aventura",
	"action":                     "ação",
	"adult":                      "adulto",
	"adventure":                  "aventura",
	"animation":                  "animação",
	"arcade":                     "arcade",
	"biography & autobiography":  "biografia e autobiografia",
	"biography":                  "biografia",
	"board game":                 "tabuleiro",
	"board":                      "tabuleiro",
	"card":                       "cartas",
	"casual":                     "casual",
	"classic":                    "clássico",
	"comedy":                     "comédia",
	"crime":                      "crime",
	"documentary":                "documentário",
	"drama":                      "drama",
	"driving":                    "corrida",
	"educational":                "educativo",
	"family & relationships":     "família e relacionamentos",
	"family":                     "família",
	"film noir":                  "filme noir",
	"game show":                  "game show",
	"fantasy":                    "fantasia",
	"fiction":                    "ficção",
	"fighting":                   "luta",
	"hack and slash":             "ação",
	"hack and slash/beat 'em up": "ação",
	"history":                    "história",
	"horror":                     "terror",
	"indie":                      "indie",
	"juvenile fiction":           "ficção juvenil",
	"kids":                       "infantil",
	"mmo":                        "mmo",
	"moba":                       "moba",
	"music":                      "musical",
	"musical":                    "musical",
	"mystery":                    "mistério",
	"philosophy":                 "filosofia",
	"platform":                   "plataforma",
	"platformer":                 "plataforma",
	"point-and-click":            "aventura",
	"psychological":              "psicológico",
	"psychology":                 "psicologia",
	"puzzle":                     "puzzle",
	"racing":                     "corrida",
	"real time strategy (rts)":   "rts",
	"real time strategy":         "rts",
	"reality":                    "reality show",
	"reality-tv":                 "reality show",
	"religion":                   "religião",
	"rhythm":                     "musical",
	"role-playing (rpg)":         "rpg",
	"role-playing":               "rpg",
	"romance":                    "romance",
	"rpg":                        "rpg",
	"rts":                        "rts",
	"sandbox":                    "sandbox",
	"sci-fi & fantasy":           "ficção científica e fantasia",
	"sci-fi":                     "ficção científica",
	"science fiction":            "ficção científica",
	"science":                    "ciência",
	"self-help":                  "autoajuda",
	"shooter":                    "fps",
	"short":                      "curta-metragem",
	"simulation":                 "simulação",
	"simulator":                  "simulação",
	"slice of life":              "cotidiano",
	"soap":                       "novela",
	"social science":             "ciências sociais",
	"sport":                      "esportes", //nolint:misspell
	"sports":                     "esportes", //nolint:misspell
	"strategy":                   "estratégia",
	"survival":                   "sobrevivência",
	"tactical":                   "estratégia",
	"talk-show":                  "talk show",
	"thriller":                   "suspense",
	"turn-based strategy (tbs)":  "estratégia",
	"turn-based strategy":        "estratégia",
	"tv movie":                   "telefilme",
	"virtual reality":            "rv",
	"visual novel":               "aventura",
	"vr":                         "rv",
	"war":                        "guerra",
	"western":                    "faroeste",
	"young adult fiction":        "ficção jovem adulto",
}
